### ISSUE TITLE
mage2gen site does not generate model and installSchema fields for 2.3 yet.

### ISSUE THREAD

**Issue by LiamKarlMitchell** [krukas/Mage2Gen#286]
Link here:
https://mage2gen.com/load/f0be1239-6c6c-4b26-bc1b-0e338c00de4a?main_version=3

Generate a 2.3 module with an Install and a Model with a field.

Expect to see InstallSchema with the fields like on 2.2 version.

Also what do you think about chaining the columns/calls per table?
```
->addColumn(
...
)->addColumn(
...
)
```

I've seen it done that way in some modules.

It would be handy to be able to add indexes and unique as well if there is a way, I've just been editing the files after the fact.

**Comment by krukas** [comment]
Hi @LiamKarlMitchell, with m2.3 you don't need the install script but can define them in etc/db_sheme.xml (https://devdocs.magento.com/guides/v2.3/extension-dev-guide/declarative-schema/db-schema.html). You have added a install snippet so that's why there are empty install scripts.

For the reason that columns are not chained is because every snippet just add the code what it needs, it doesn't know anything from other snippets so that's why we cant chain them.
