### ISSUE TITLE
Upgrading the database resource using the version number

### ISSUE THREAD

**Issue by shinesoftware** [krukas/Mage2Gen#52]
Ok! I have created the module and now I have downloaded it from your site to my store but... I forgot to add a db field in my model... and now?
I have to go to your website to add my new db field. I have to download again the module and I have to install it in my store but... the new field has been not created in the database ... why?

Because the setup_version remains "1.0.0" and Magento doesn't upgrade the databse when I execute the command by the bash:

> php -f bin/magento setup:upgrade

So I suggest you to save the version of the module when the user download the module and offer a way to maintain the module releases.

Regards

**Comment by krukas** [comment]
This can indeed be a real nice feature. we thought about diff support. Currently the implementation only support the first version of the module. There is no support to have multiple versions of the module and track witch snippets are changed between versions and how the generation of the module effect this.

One of the reasons this is not supported is because the module file are likely to be changed and you can not easily apply the new Mage2Gen changes over the module changes. This is also the reason why we added 'copy to clipboard' to easier copy one specific file that is new you want to add to you module.

For now I will close this ticket, but if you have ideas about making this work I am glad to hear them.
