### ISSUE TITLE
Columns which should be displayed on admin grid

### ISSUE THREAD

**Issue by VincentMarmiesse** [krukas/Mage2Gen#78]
Hello,

When creating a model, we can choose if we want the fields to be displayed on admin grid or not.
All columns with the selected option are added to the file `view/adminhtml/ui_component/module_model_index.xml`, which is ok.

Then, the `actionsColumn` is added, which is also ok.

But after this `actionsColumn`, the columns which were not selected to be displayed on the admin grid are added. This is causing an error and blocks the admin grid render. The fix is to remove all columns after the `actionsColumn`.

I would like to make a PR but in the `model.py` file, I see the `actionsColumn` part but I don't see how you handle the Adminhtml grid checkbox.

Thanks!

**Comment by krukas** [comment]
I haven't seen the crash with actionsColumn need to look into that. The problem is that snippets don't now what other snippets do. 

A way to solve this is in the generation level where we don't merge everything on the fly but on the generation. then we can keep track of the snippets called an say to a snippet you are the last snippet for the generation and do some extra stuff like adding a actionsColumn.
